# Generated by Django 5.2.5 on 2025-08-19 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ADJOURNED', 'Adjourned')], default='OPEN', max_length=20)),
                ('next_hearing_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.casefile')),
            ],
        ),
        migrations.AddIndex(
            model_name='casefile',
            index=models.Index(fields=['client_name'], name='cases_casef_client__706e48_idx'),
        ),
        migrations.AddIndex(
            model_name='casefile',
            index=models.Index(fields=['status'], name='cases_casef_status_0be19d_idx'),
        ),
        migrations.AddIndex(
            model_name='casefile',
            index=models.Index(fields=['next_hearing_date'], name='cases_casef_next_he_a1a813_idx'),
        ),
    ]
