# Generated by Django 5.2.5 on 2025-08-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ADJOURNED', 'Adjourned'), ('PENDING', 'Pending')], default='OPEN', max_length=20),
        ),
    ]
